telegram:
  token: 6455629506:AAEQAFzzB0RYxpyYRZEsx2ZuLWN_dgcA_EM
  chatIDList:
    - 1247260748
  adminID: 1247260748

database:
  host: db
  port: 5432
  password: 12345
  user: postgres
  dbname: postgres