telegram:
  token: 6429809481:AAH8-2HWiAoN7K5zMx3hJFMqwjfb9ci7B2E
  chatIDList:
    - 1167687440
  adminID: 1167687440

database:
  host: telebot-db
#  host: localhost
  port: 5432
  password: telebot13572468
  user: telebot
  dbname: basket_stat