telegram:
  token: hh
  chatIDList:
    - 1167687440
  adminID: 1167687440

database:
  host: telebot-db
#  host: localhost
  port: 5432
  password: telebot13572468
  user: telebot
  dbname: basket_stat