version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: "postgres"
    ports:
      - "5433:5432"
  web:
    build:
      dockerfile: Dockerfile
    container_name: my-app
    depends_on:
      - db
    ports:
      - "8080:8080"